export default {
  login: "WOLFIEEEE",
  id: 50989808,
  node_id: "MDQ6VXNlcjUwOTg5ODA4",
  avatar_url: "https://avatars3.githubusercontent.com/u/50989808?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/WOLFIEEEE",
  html_url: "https://github.com/WOLFIEEEE",
  followers_url: "https://api.github.com/users/WOLFIEEEE/followers",
  following_url: "https://api.github.com/users/WOLFIEEEE/following{/other_user}",
  gists_url: "https://api.github.com/users/WOLFIEEEE/gists{/gist_id}",
  starred_url: "https://api.github.com/users/WOLFIEEEE/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/WOLFIEEEE/subscriptions",
  organizations_url: "https://api.github.com/users/WOLFIEEEE/orgs",
  repos_url: "https://api.github.com/users/WOLFIEEEE/repos",
  events_url: "https://api.github.com/users/WOLFIEEEE/events{/privacy}",
  received_events_url: "https://api.github.com/users/WOLFIEEEE/received_events",
  type: "User",
  site_admin: false,
  name: "KHUSHWANT PARIHAR",
  company: null,
  blog: "https://khushwant.netlify.app/",
  location: null,
  email: null,
  hireable: null,
  bio: "A CSE 3rd year student Curretly Started with python Language I'm familiar with C++ C Hackerrank 5* in C++ can't say same about other language",
  twitter_username: null,
  public_repos: 11,
  public_gists: 0,
  followers: 2,
  following: 2,
  created_at: "2019-05-24T11:48:31Z",
  updated_at: "2021-01-05T18:48:11Z"
  };