export default [
    {
    login: "sasheshsingh",
    id: 45543817,
    node_id: "MDQ6VXNlcjQ1NTQzODE3",
    avatar_url: "https://avatars0.githubusercontent.com/u/45543817?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/sasheshsingh",
    html_url: "https://github.com/sasheshsingh",
    followers_url: "https://api.github.com/users/sasheshsingh/followers",
    following_url: "https://api.github.com/users/sasheshsingh/following{/other_user}",
    gists_url: "https://api.github.com/users/sasheshsingh/gists{/gist_id}",
    starred_url: "https://api.github.com/users/sasheshsingh/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/sasheshsingh/subscriptions",
    organizations_url: "https://api.github.com/users/sasheshsingh/orgs",
    repos_url: "https://api.github.com/users/sasheshsingh/repos",
    events_url: "https://api.github.com/users/sasheshsingh/events{/privacy}",
    received_events_url: "https://api.github.com/users/sasheshsingh/received_events",
    type: "User",
    site_admin: false
    },
    {
    login: "seungjae02",
    id: 66529019,
    node_id: "MDQ6VXNlcjY2NTI5MDE5",
    avatar_url: "https://avatars2.githubusercontent.com/u/66529019?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/seungjae02",
    html_url: "https://github.com/seungjae02",
    followers_url: "https://api.github.com/users/seungjae02/followers",
    following_url: "https://api.github.com/users/seungjae02/following{/other_user}",
    gists_url: "https://api.github.com/users/seungjae02/gists{/gist_id}",
    starred_url: "https://api.github.com/users/seungjae02/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/seungjae02/subscriptions",
    organizations_url: "https://api.github.com/users/seungjae02/orgs",
    repos_url: "https://api.github.com/users/seungjae02/repos",
    events_url: "https://api.github.com/users/seungjae02/events{/privacy}",
    received_events_url: "https://api.github.com/users/seungjae02/received_events",
    type: "User",
    site_admin: false
    }
    ];